name: Check for Debug Statements

on:
  pull_request:
    branches:
      - '**'  # Trigger on PRs to any branch

jobs:
  check-debug:
    name: Scan for System.debug and console.log
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to get full Git history

      - name: Fetch base branch
        run: git fetch origin ${{ github.base_ref }}

      - name: Run debug check with snippet
        shell: pwsh
        run: ./detect_systemdebug.ps1 ${{ github.base_ref }}

