name: CheckDebug

on:
  pull_request:
    branches:
      - '**'   # Trigger on any PR branch

jobs:
  check-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # fetch full history

      - name: Prepare debug directory and copy script
        run: |
          mkdir -p ${{ github.workspace }}/debug
          cp ${{ github.workspace }}/detect_systemdebug.ps1 ${{ github.workspace }}/debug/
          chmod -x detect_systemdebug.ps1

      - name: Fail PR if System.debug or console.log found
        shell: pwsh
        run: |
          cd ${{ github.workspace }}
          ls -l
          chmod -x detect_systemdebug.ps1
          ./detect_systemdebug.ps1
