name: Check for Debug Statements

on:
  pull_request:
    branches:
      - '**'  # Trigger on PRs to any branch

jobs:
  check-debug:
    name: Scan for System.debug and console.log
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to get full Git history

      - name: Fetch base branch
        run: git fetch origin ${{ github.base_ref }}

      - name: Run debug scan script
        shell: pwsh
        run: |
          # Save the script to file
          $scriptContent = @'
          # (Paste the entire PowerShell script content here)
          '@

          $scriptPath = "./detect_systemdebug.ps1"
          $scriptContent | Out-File -FilePath $scriptPath -Encoding utf8

          # Run the script
          pwsh $scriptPath

