name: Scan PR for System.debug and console.log
 
on:
  workflow_dispatch: # Manual trigger
 
jobs:
  check-debug:
    name: Scan PR Delta
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed to get full git history for PR comparison
 
      - name: Set script permissions
        run: |
          mkdir -p debug
          cp detect_systemdebug.ps1 debug/
          chmod +x debug/detect_systemdebug.ps1
 
      - name: Run debug detection PowerShell script
        shell: pwsh
        run: |
          ./debug/detect_systemdebug.ps1
