name: IFT-DEPLOY-TO-QA
on:
  workflow_dispatch:
    inputs:
      MANUAL_COMMIT_ID:
        description: 'Commit ID to compare from (leave as "default" to auto-calculate)'
        required: false
        default: 'default'
      TEST_LEVEL:
        description: 'Enter type of test case to be checked'
        required: true
        default: 'NoTestRun'
        type: choice
        options:
          - NoTestRun
          - RunSpecifiedTests
          - RunLocalTests
      TEST_CLASSES:
        description: 'Comma-separated test class names (required for RunSpecifiedTests)'
        required: false
        default: ''

jobs:
  sfdx-deploy:
    runs-on: ubuntu-latest

    env:
      ORG_USER: ${{ secrets.TEST_ORG_USER }}
      ORG_PASSWORD: ${{ secrets.TEST_ORG_PASSWORD }}
      ORG_URL: ${{ secrets.TEST_ORG_URL }}

    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v4
        with:
          ref: teambranch
          fetch-depth: 0  # Ensures full commit history is available

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install Salesforce CLI
        run: npm install -g sfdx-cli

      - name: Install sfpowerkit plugin
        run: echo 'y' | sfdx plugins:install sfpowerkit

      - name: Show SFDX version
        run: sfdx --version

      - name: Prepare deployment and run SFDX commands
        run: |
          set -e

          # Input parameters
          TEST_LEVEL="${{ github.event.inputs.TEST_LEVEL }}"
          TEST_CLASSES="${{ github.event.inputs.TEST_CLASSES }}"
          MANUAL_COMMIT_ID="${{ github.event.inputs.MANUAL_COMMIT_ID }}"

          # Handle RunSpecifiedTests case
          if [[ "$TEST_LEVEL" == "RunSpecifiedTests" ]]; then
            TEST_CLASSES=$(echo "$TEST_CLASSES" | tr -d ' ')
            if [[ -z "$TEST_CLASSES" || "$TEST_CLASSES" =~ ^[Nn]ull$ ]]; then
              echo "❌ Please specify TEST_CLASSES when using RunSpecifiedTests"
              exit 1
            fi
            TEST_LEVEL="$TEST_LEVEL -r $TEST_CLASSES"
          fi

          echo "🧾 TEST_LEVEL: $TEST_LEVEL"

          # Get Git commit IDs
          LATEST_COMMIT_ID=$(git log -n 1 --pretty=format:'%H')
          if [[ "$MANUAL_COMMIT_ID" == "default" ]]; then
            MANUAL_COMMIT_ID=$(git log --format="%P" -n 1 | cut -d ' ' -f1)
          fi

          echo "🔁 Previous Commit ID: $MANUAL_COMMIT_ID"
          echo "🔄 Latest Commit ID:   $LATEST_COMMIT_ID"

          # Validate commit IDs
          if [[ -z "$MANUAL_COMMIT_ID" || -z "$LATEST_COMMIT_ID" ]]; then
            echo "❌ One or both commit IDs are empty. Cannot perform diff."
            exit 1
          fi

          echo "📦 Generating Delta Package"
          sfdx sfpowerkit:project:diff -r "$MANUAL_COMMIT_ID" -t "$LATEST_COMMIT_ID" -d Delta_pkg

          if [ ! -d "Delta_pkg" ]; then
            echo "❗ No diff found — nothing to deploy."
            exit 1
          fi

          echo "🔐 Authenticating to Salesforce Org"
          sfdx sfpowerkit:auth:login -u "$ORG_USER" -p "$ORG_PASSWORD" -r "$ORG_URL"

          echo "🧪 Validating Deployment"
          sfdx force:source:deploy -c -p Delta_pkg/force-app -u "$ORG_USER" -l "$TEST_LEVEL"

          echo "🚀 Deploying to Org"
          sfdx force:source:deploy -p Delta_pkg/force-app -u "$ORG_USER"

          echo "🎉 Deployment completed successfully"

